name: 'Build & Push Selected Docker Images to Docker Hub'

on:
  push:
    branches:
      - main

env:
  DOCKER_REPO_BROKER_SERVICE: orochinetwork/zkdb-broker-service
  DOCKER_REPO_PROOF_SERVICE: orochinetwork/zkdb-proof-service
  DOCKER_REPO_SERVERLESS: orochinetwork/zkdb-serverless
  NPM_ACCESS_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}

jobs:
  detect-changes:
    name: Detect Changes
    # runs-on: [self-hosted, linux]
    runs-on: ubuntu-latest
    outputs:
      filtered_packages: ${{ steps.filter.outputs.filtered_packages }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch enough commit history

      - name: Detect changed packages
        id: changed
        run: |
          # Find the last two merge commits
          LAST_MERGE=$(git log --merges --pretty=format:'%H' -n 10)
          MERGE_ARRAY=($LAST_MERGE)
          LAST_MERGE_COMMIT=${MERGE_ARRAY[0]}
          PREV_MERGE_COMMIT=${MERGE_ARRAY[9]}
          
          # Show the two merge commits
          echo "Last merge commit: $LAST_MERGE_COMMIT"
          echo "Previous merge commit: $PREV_MERGE_COMMIT"
          
          # Get the diff between the two merge commits
          CHANGED_PACKAGES=$(git diff --name-only $PREV_MERGE_COMMIT $LAST_MERGE_COMMIT -- packages/ | cut -d '/' -f 1-2 | sort -u)
          echo "Detected changes: $CHANGED_PACKAGES"

          # Clean up carriage returns or special characters and split on new lines
          CLEANED_PACKAGES=$(echo "$CHANGED_PACKAGES" | tr -d '\r' | tr '\n' ' ')
          echo "Cleaned packages: $CLEANED_PACKAGES"

          # Save cleaned package names to environment
          echo "changed_packages=$CLEANED_PACKAGES" >> $GITHUB_ENV

      - name: Filter packages using case statement and map to numbers
        id: filter
        run: |
          CHANGED_PACKAGES="${{ env.changed_packages }}"
          FILTERED_PACKAGES=""

          # Debugging - print out each package to see what's being processed
          echo "Changed packages: $CHANGED_PACKAGES"

          # Split the CHANGED_PACKAGES string into an array
          IFS=' ' read -r -a PACKAGE_ARRAY <<< "$CHANGED_PACKAGES"

          # Declare an associative array to map package names to numbers
          declare -A PACKAGE_MAP
          PACKAGE_MAP["packages/serverless"]=1
          PACKAGE_MAP["packages/broker-service"]=2
          PACKAGE_MAP["packages/proof-service"]=3

          # Loop through the detected changes and map the packages to numbers
          for PACKAGE in "${PACKAGE_ARRAY[@]}"; do
            case $PACKAGE in
              "packages/serverless")
                FILTERED_PACKAGES="$FILTERED_PACKAGES ${PACKAGE_MAP["packages/serverless"]}"
                echo "serverless changed (mapped to 1)"
                ;;
              "packages/broker-service")
                FILTERED_PACKAGES="$FILTERED_PACKAGES ${PACKAGE_MAP["packages/broker-service"]}"
                echo "broker-service changed (mapped to 2)"
                ;;
              "packages/proof-service")
                FILTERED_PACKAGES="$FILTERED_PACKAGES ${PACKAGE_MAP["packages/proof-service"]}"
                echo "proof-service changed (mapped to 3)"
                ;;
              *)
                echo "No match for package: $PACKAGE"
                ;;
            esac
          done

          # Trim any leading/trailing spaces in FILTERED_PACKAGES
          FILTERED_PACKAGES=$(echo $FILTERED_PACKAGES | xargs)

          # Output the mapped numbers using Environment Files and set job output
          if [ -z "$FILTERED_PACKAGES" ]; then
            echo "No required packages changed."
            exit 0
          else
            echo "filtered_packages=$FILTERED_PACKAGES" >> $GITHUB_OUTPUT
          fi

  build:
    name: Build & Push Docker Images
    needs: detect-changes
    runs-on: [self-hosted, linux]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build & Push Broker Service Image
        run: |
          echo "Filtered Packages: ${{ needs.detect-changes.outputs.filtered_packages }}"
          if [[ "${{ needs.detect-changes.outputs.filtered_packages }}" == *"2"* ]]; then
            echo "Building and pushing Broker Service..."
            echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_ACCESS_TOKEN }}" > npm-token
            docker build -t ${{ env.DOCKER_REPO_BROKER_SERVICE }}:latest \
              -f packages/broker-service/Dockerfile \
              --platform=linux/amd64 \
              --secret id=npm,src=npm-token .
            docker tag ${{ env.DOCKER_REPO_BROKER_SERVICE }}:latest ${{ env.DOCKER_REPO_BROKER_SERVICE }}:${{ github.sha }}
            docker push ${{ env.DOCKER_REPO_BROKER_SERVICE }}:latest
            docker push ${{ env.DOCKER_REPO_BROKER_SERVICE }}:${{ github.sha }}
          else
            echo "Broker Service not in changed packages."
          fi

          # Set up SSH for GitOps push
          eval $(ssh-agent -s)
          echo "${{ secrets.SSH_KEY }}" | tr -d '\r' | ssh-add -
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          
          version-test=$(echo "${{ github.sha }}""
          # Process each service dynamically using arrays
          for i in ${!SERVICES[@]}; do
            SERVICE="${SERVICES[$i]}"
            DOCKER_REPO="${DOCKER_REPOS[$i]}"
            VALUES_PATH="${VALUES_PATHS[$i]}"
            NUM=$((i + 1))

            # Ensure Docker repo is not empty before proceeding
            if [[ -n "$DOCKER_REPO" && "${{ needs.detect-changes.outputs.filtered_packages }}" == *"$NUM"* ]]; then
              echo "Building and pushing $SERVICE..."
              echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_ACCESS_TOKEN }}" > npm-token 

              # Build the Docker image with a valid tag
              docker build -t "$DOCKER_REPO:latest" \
                -f "packages/$SERVICE/Dockerfile" \
                --secret id=npm,src=./npm-token \
                --platform=linux/amd64 .
              docker push "$DOCKER_REPO:latest"
              docker push "$DOCKER_REPO:${{ env.version }}"

              # GitOps push for the service
              # Clone the GitOps repository (once for all services)
              git config --global user.name "GitOps Updater"
              git config --global user.email "minhan112001@gmail.com"
              git clone git@github.com:ZKP-Labs/test-argoCD.git
              cd test-argoCD
              git checkout ${GITOPSBRANCH}
              sed -i "s| tag: .*| tag: ${version}|" "$VALUES_PATH"
              git fetch origin
              git add "$VALUES_PATH"
              git commit -m "$SERVICE: Update version to ${version}"
              git push origin ${GITOPSBRANCH}
            else
              echo "$SERVICE not changed or invalid Docker repo, skipping."
            fi
          done

          # Clean up GitOps repo
          cd ..
          rm -rf test-argoCD
